application: ahorcadocanciones
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /images
  static_dir: images

- url: /audios
  static_dir: audios

- url: /stylesheets
  static_dir: stylesheets

- url: /js
  mime_type: font/truetype
  static_dir: js

- url: /font
  mime_type: font/truetype
  static_dir: font

- url: /font/roboto
  mime_type: font/truetype
  static_dir: font/roboto

- url: /font/material-design-icons
  mime_type: image/x-icon
  static_dir: font/material-design-icons

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest

- name: webapp2
  version: "2.5.2"
